### ISSUE TITLE
Support top-level arrays in ld+json

### ISSUE THREAD

**Issue by woofsbane** [arcetros/scrape-recipe-schema#25]
`getRecipeData` assumes that the top-level object in the ld+json schema is an object. However, it seems the top-level sometimes appears as an array of objects.

Example: https://www.simplyrecipes.com/recipes/lasagna/

**Comment by arcetros** [comment]
@woofsbane, I have fixed the issue in the following repository: https://github.com/dimfu/recipe-scraper. I have rewritten the code to address the issue and improve it. Please note that `scrape-recipe-schema` will no longer receive any updates, as I no longer use that account since it was a burner account.
